### ISSUE TITLE
pinyingpt-concat 模型复现问题

### ISSUE THREAD

**Issue by metaescape** [VisualJoyce/Transformers4IME#1]
感谢您的论文工作和代码分享，我在复现过程中，基于 public 和 ours (aihijo/gpt2-zh-21k)在 data/benchmarks/PD/samples_0.json 上得到了和论文 table3 一样的结果。

但是 aihijo/transformers4ime-pinyingpt-concat 模型评测却不符合预期，比如选择data/benchmarks/WD/samples_体育_0-3_10+.json 作为 benchmark 文件时，在 aihijo/gpt2-zh-21k 模型上得到的结果是：
```
top 1 accuracy: 71.85000000000001
top 5 accuracy: 83.35000000000001
top 10 accuracy: 83.85000000000001
```

用 public 模型得到结果是：
```
top 1 accuracy: 62.5
top 5 accuracy: 75.25
top 10 accuracy: 76.44999999999999
```

这是合理的, 但用 aihijo/transformers4ime-pinyingpt-concat 模型推理得到的却是：

```
top 1 accuracy: , 42.15
top 5 accuracy:  52.75
top 10 accuracy:  53.55
```

有拼音作为上下文，又是在 WUDAO 测试集，预期结果应该要比aihijo/gpt2-zh-21k 更好才对,但这里却下降了不少。

我用的命令是：

```
python3 benchmarks.py --samples_json data/benchmarks/WD/samples_体育_0-3_10+.json \
  --pretrained_model_name_or_path data/pretrained_models/gpt2-zh-21k \
  --model_name pinyingpt-concat \
  --additional_special_tokens data/pretrained/additional_special_tokens.json \
  --pinyin2char_json data/pretrained/pinyin2char.json \
  --pinyin_logits_processor_cls pinyingpt-concat \
  --num_beams 16 \
  --abbr_mode none\
  --best_pt data/pretrained_models/pinyingpt-concat/pytorch_model.bin
```

其中 data/pretrained_models/pinyingpt-concat/pytorch_model.bin 是从https://huggingface.co/aihijo/transformers4ime-pinyingpt-concat/tree/main 下载的，运行中显示已经加载 best ckpt 并且检查了模型的输入和输出格式，应该都没有问题，不知为何最后效果会更差?

**Comment by Vimos** [comment]
多谢关注！

这个模型是首字母的，`abbr_mode`应该选择 full

**Comment by metaescape** [comment]
好的，谢谢
